export const FETCH_FIRST_HUNDRED_WORDS = 'FETCH_FIRST_HUNDRED_WORDS';
export const FETCH_WORD = 'FETCH_WORD';
export const SET_PAGE = 'SET_PAGE';
export const GET_AMOUNT_OF_PAGES = 'GET_AMOUNT_OF_PAGES';
