export const wordsActionTypes = {
  FETCH_FIRST_HUNDRED_WORDS: 'FETCH_FIRST_HUNDRED_WORDS',
  FETCH_WORD: 'FETCH_WORD',
  SET_PAGE: 'SET_PAGE',
  GET_AMOUNT_OF_PAGES: 'GET_AMOUNT_OF_PAGES',
  ADD_PAGE: 'ADD_PAGE',
  DECREMENT_PAGE: 'DECREMENT_PAGE'
} 
